### ISSUE TITLE
Update Gem on rubygems

### ISSUE THREAD

**Issue by jimkoen** [dm-drogeriemarkt/foreman_netbox#51]
As far as I can tell, there was a small fix to provide support to Netbox v2.11
However that fix seems to not have been propagated to rubygems.

Could you update the Gem so that we can pull from rubygems instead of cloning the git repo and building it from there?

**Comment by danielwieberneit** [comment]
Hi @jimkoen,
we have an issue with our pipeline. We can propagate to rubygems, after we fixed this.

**Comment by danielwieberneit** [comment]
Hi @jimkoen 
we fix our pipeline issue. I uploaded gem Version 1.1.0 to https://rubygems.org/gems/foreman_netbox
